name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          cd custom_components/ems_v1
          zip -r ../../ems_v1.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ems_v1
          path: ems_v1.zip
